/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa.interfaz;

/**
 *
 * @author Santiago
 */
public class PanelNovedades extends javax.swing.JPanel {

    /**
     * Creates new form PanelNovedades
     */
    public PanelNovedades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        auxTransporteGroup = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Cedula = new javax.swing.JLabel();
        valorCedula = new javax.swing.JLabel();
        salarioBasico = new javax.swing.JLabel();
        valorSalarioBasico = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        valorHora = new javax.swing.JLabel();
        nombres = new javax.swing.JLabel();
        valorNombres = new javax.swing.JLabel();
        auxTransporte = new javax.swing.JLabel();
        auxTransNo = new javax.swing.JRadioButton();
        auxTransSI = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        valorApellidos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        Cedula.setText("Cédula:");

        valorCedula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valorCedula.setText("jLabel1");

        salarioBasico.setText("Salario Básico");

        valorSalarioBasico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valorSalarioBasico.setText("jLabel1");

        hora.setText("Valor Hora:");

        valorHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valorHora.setText("jLabel2");

        nombres.setText("Nombres:");

        valorNombres.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valorNombres.setText("jLabel1");

        auxTransporte.setText("Auxilio de Transporte:");

        auxTransNo.setBackground(new java.awt.Color(255, 255, 255));
        auxTransporteGroup.add(auxTransNo);
        auxTransNo.setSelected(true);
        auxTransNo.setText("No");
        auxTransNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auxTransNoActionPerformed(evt);
            }
        });

        auxTransSI.setBackground(new java.awt.Color(255, 255, 255));
        auxTransporteGroup.add(auxTransSI);
        auxTransSI.setText("Si");
        auxTransSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auxTransSIActionPerformed(evt);
            }
        });

        jLabel1.setText("Apellidos");

        valorApellidos.setText("jLabel4");

        jLabel2.setText("Trabajo complementario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(salarioBasico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(valorSalarioBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(valorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nombres)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(valorNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(231, 231, 231)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(auxTransporte)
                                    .addComponent(hora))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(valorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valorApellidos)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(auxTransNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(auxTransSI))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombres)
                    .addComponent(valorNombres)
                    .addComponent(jLabel1)
                    .addComponent(valorApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorCedula)
                    .addComponent(auxTransporte)
                    .addComponent(auxTransNo)
                    .addComponent(auxTransSI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorHora)
                    .addComponent(valorSalarioBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora)
                    .addComponent(salarioBasico))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        valorApellidos.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void auxTransNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auxTransNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auxTransNoActionPerformed

    private void auxTransSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auxTransSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auxTransSIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.JRadioButton auxTransNo;
    private javax.swing.JRadioButton auxTransSI;
    private javax.swing.JLabel auxTransporte;
    private javax.swing.ButtonGroup auxTransporteGroup;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel nombres;
    private javax.swing.JLabel salarioBasico;
    private javax.swing.JLabel valorApellidos;
    private javax.swing.JLabel valorCedula;
    private javax.swing.JLabel valorHora;
    private javax.swing.JLabel valorNombres;
    private javax.swing.JLabel valorSalarioBasico;
    // End of variables declaration//GEN-END:variables
}
